robot1:
  controller_manager:
    ros__parameters:
      update_rate: 100 #Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_group_controller:
        type: position_controllers/JointGroupPositionController

  joint_group_controller:
    ros__parameters:
      joints:
        - robot1_FR_hip_joint
        - robot1_FR_thigh_joint
        - robot1_FR_calf_joint
        - robot1_FL_hip_joint
        - robot1_FL_thigh_joint
        - robot1_FL_calf_joint
        - robot1_RR_hip_joint
        - robot1_RR_thigh_joint
        - robot1_RR_calf_joint
        - robot1_RL_hip_joint
        - robot1_RL_thigh_joint
        - robot1_RL_calf_joint

robot2:
  controller_manager:
    ros__parameters:
      update_rate: 100 #Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_group_controller:
        type: position_controllers/JointGroupPositionController

  joint_group_controller:
    ros__parameters:
      joints:
        - robot2_FR_hip_joint
        - robot2_FR_thigh_joint
        - robot2_FR_calf_joint
        - robot2_FL_hip_joint
        - robot2_FL_thigh_joint
        - robot2_FL_calf_joint
        - robot2_RR_hip_joint
        - robot2_RR_thigh_joint
        - robot2_RR_calf_joint
        - robot2_RL_hip_joint
        - robot2_RL_thigh_joint
        - robot2_RL_calf_joint

robot3:
  controller_manager:
    ros__parameters:
      update_rate: 100 #Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_group_controller:
        type: position_controllers/JointGroupPositionController

  joint_group_controller:
    ros__parameters:
      joints:
        - robot3_FR_hip_joint
        - robot3_FR_thigh_joint
        - robot3_FR_calf_joint
        - robot3_FL_hip_joint
        - robot3_FL_thigh_joint
        - robot3_FL_calf_joint
        - robot3_RR_hip_joint
        - robot3_RR_thigh_joint
        - robot3_RR_calf_joint
        - robot3_RL_hip_joint
        - robot3_RL_thigh_joint
        - robot3_RL_calf_joint

robot4:
  controller_manager:
    ros__parameters:
      update_rate: 100 #Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_group_controller:
        type: position_controllers/JointGroupPositionController

  joint_group_controller:
    ros__parameters:
      joints:
        - robot4_FR_hip_joint
        - robot4_FR_thigh_joint
        - robot4_FR_calf_joint
        - robot4_FL_hip_joint
        - robot4_FL_thigh_joint
        - robot4_FL_calf_joint
        - robot4_RR_hip_joint
        - robot4_RR_thigh_joint
        - robot4_RR_calf_joint
        - robot4_RL_hip_joint
        - robot4_RL_thigh_joint
        - robot4_RL_calf_joint

robot5:
  controller_manager:
    ros__parameters:
      update_rate: 100 #Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_group_controller:
        type: position_controllers/JointGroupPositionController

  joint_group_controller:
    ros__parameters:
      joints:
        - robot5_FR_hip_joint
        - robot5_FR_thigh_joint
        - robot5_FR_calf_joint
        - robot5_FL_hip_joint
        - robot5_FL_thigh_joint
        - robot5_FL_calf_joint
        - robot5_RR_hip_joint
        - robot5_RR_thigh_joint
        - robot5_RR_calf_joint
        - robot5_RL_hip_joint
        - robot5_RL_thigh_joint
        - robot5_RL_calf_joint

robot6:
  controller_manager:
    ros__parameters:
      update_rate: 100 #Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_group_controller:
        type: position_controllers/JointGroupPositionController

  joint_group_controller:
    ros__parameters:
      joints:
        - robot6_FR_hip_joint
        - robot6_FR_thigh_joint
        - robot6_FR_calf_joint
        - robot6_FL_hip_joint
        - robot6_FL_thigh_joint
        - robot6_FL_calf_joint
        - robot6_RR_hip_joint
        - robot6_RR_thigh_joint
        - robot6_RR_calf_joint
        - robot6_RL_hip_joint
        - robot6_RL_thigh_joint
        - robot6_RL_calf_joint

# robot7:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - robot1_FR_hip_joint
#         - robot1_FR_thigh_joint
#         - robot1_FR_calf_joint
#         - robot1_FL_hip_joint
#         - robot1_FL_thigh_joint
#         - robot1_FL_calf_joint
#         - robot1_RR_hip_joint
#         - robot1_RR_thigh_joint
#         - robot1_RR_calf_joint
#         - robot1_RL_hip_joint
#         - robot1_RL_thigh_joint
#         - robot1_RL_calf_joint

# robot8:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - robot1_FR_hip_joint
#         - robot1_FR_thigh_joint
#         - robot1_FR_calf_joint
#         - robot1_FL_hip_joint
#         - robot1_FL_thigh_joint
#         - robot1_FL_calf_joint
#         - robot1_RR_hip_joint
#         - robot1_RR_thigh_joint
#         - robot1_RR_calf_joint
#         - robot1_RL_hip_joint
#         - robot1_RL_thigh_joint
#         - robot1_RL_calf_joint

# robot9:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - robot1_FR_hip_joint
#         - robot1_FR_thigh_joint
#         - robot1_FR_calf_joint
#         - robot1_FL_hip_joint
#         - robot1_FL_thigh_joint
#         - robot1_FL_calf_joint
#         - robot1_RR_hip_joint
#         - robot1_RR_thigh_joint
#         - robot1_RR_calf_joint
#         - robot1_RL_hip_joint
#         - robot1_RL_thigh_joint
#         - robot1_RL_calf_joint

# robot10:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - robot1_FR_hip_joint
#         - robot1_FR_thigh_joint
#         - robot1_FR_calf_joint
#         - robot1_FL_hip_joint
#         - robot1_FL_thigh_joint
#         - robot1_FL_calf_joint
#         - robot1_RR_hip_joint
#         - robot1_RR_thigh_joint
#         - robot1_RR_calf_joint
#         - robot1_RL_hip_joint
#         - robot1_RL_thigh_joint
#         - robot1_RL_calf_joint