robot1:
  controller_manager:
    ros__parameters:
      update_rate: 100 #Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_group_controller:
        type: position_controllers/JointGroupPositionController

  joint_group_controller:
    ros__parameters:
      joints:
        - FR_hip_joint
        - FR_thigh_joint
        - FR_calf_joint
        - FL_hip_joint
        - FL_thigh_joint
        - FL_calf_joint
        - RR_hip_joint
        - RR_thigh_joint
        - RR_calf_joint
        - RL_hip_joint
        - RL_thigh_joint
        - RL_calf_joint

robot2:
  controller_manager:
    ros__parameters:
      update_rate: 100 #Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_group_controller:
        type: position_controllers/JointGroupPositionController

  joint_group_controller:
    ros__parameters:
      joints:
        - FR_hip_joint
        - FR_thigh_joint
        - FR_calf_joint
        - FL_hip_joint
        - FL_thigh_joint
        - FL_calf_joint
        - RR_hip_joint
        - RR_thigh_joint
        - RR_calf_joint
        - RL_hip_joint
        - RL_thigh_joint
        - RL_calf_joint

# robot3:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - FR_hip_joint
#         - FR_thigh_joint
#         - FR_calf_joint
#         - FL_hip_joint
#         - FL_thigh_joint
#         - FL_calf_joint
#         - RR_hip_joint
#         - RR_thigh_joint
#         - RR_calf_joint
#         - RL_hip_joint
#         - RL_thigh_joint
#         - RL_calf_joint

# robot4:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - FR_hip_joint
#         - FR_thigh_joint
#         - FR_calf_joint
#         - FL_hip_joint
#         - FL_thigh_joint
#         - FL_calf_joint
#         - RR_hip_joint
#         - RR_thigh_joint
#         - RR_calf_joint
#         - RL_hip_joint
#         - RL_thigh_joint
#         - RL_calf_joint

# robot5:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - FR_hip_joint
#         - FR_thigh_joint
#         - FR_calf_joint
#         - FL_hip_joint
#         - FL_thigh_joint
#         - FL_calf_joint
#         - RR_hip_joint
#         - RR_thigh_joint
#         - RR_calf_joint
#         - RL_hip_joint
#         - RL_thigh_joint
#         - RL_calf_joint

# robot6:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - FR_hip_joint
#         - FR_thigh_joint
#         - FR_calf_joint
#         - FL_hip_joint
#         - FL_thigh_joint
#         - FL_calf_joint
#         - RR_hip_joint
#         - RR_thigh_joint
#         - RR_calf_joint
#         - RL_hip_joint
#         - RL_thigh_joint
#         - RL_calf_joint

# robot7:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - FR_hip_joint
#         - FR_thigh_joint
#         - FR_calf_joint
#         - FL_hip_joint
#         - FL_thigh_joint
#         - FL_calf_joint
#         - RR_hip_joint
#         - RR_thigh_joint
#         - RR_calf_joint
#         - RL_hip_joint
#         - RL_thigh_joint
#         - RL_calf_joint

# robot8:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - FR_hip_joint
#         - FR_thigh_joint
#         - FR_calf_joint
#         - FL_hip_joint
#         - FL_thigh_joint
#         - FL_calf_joint
#         - RR_hip_joint
#         - RR_thigh_joint
#         - RR_calf_joint
#         - RL_hip_joint
#         - RL_thigh_joint
#         - RL_calf_joint

# robot9:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - FR_hip_joint
#         - FR_thigh_joint
#         - FR_calf_joint
#         - FL_hip_joint
#         - FL_thigh_joint
#         - FL_calf_joint
#         - RR_hip_joint
#         - RR_thigh_joint
#         - RR_calf_joint
#         - RL_hip_joint
#         - RL_thigh_joint
#         - RL_calf_joint

# robot10:
#   controller_manager:
#     ros__parameters:
#       update_rate: 100 #Hz

#       joint_state_broadcaster:
#         type: joint_state_broadcaster/JointStateBroadcaster

#       joint_group_controller:
#         type: position_controllers/JointGroupPositionController

#   joint_group_controller:
#     ros__parameters:
#       joints:
#         - FR_hip_joint
#         - FR_thigh_joint
#         - FR_calf_joint
#         - FL_hip_joint
#         - FL_thigh_joint
#         - FL_calf_joint
#         - RR_hip_joint
#         - RR_thigh_joint
#         - RR_calf_joint
#         - RL_hip_joint
#         - RL_thigh_joint
#         - RL_calf_joint